module.exports = {
    'english': 'Inglés',
    'french': 'Français',
    'spanish': 'Español',
    'titulo' : 'Maquina de Aventura',
    'tit_about' : 'Acerca de Camilo',
    'about' : 'ACERCA DE MI',
    'whats' : 'QUE ES?',
    'upload' : 'SUBIR AUDIO',
    'texto_ad' : 'Que es?',
    'texto_ad_t' : 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit,sed diam nonummy nibh euismod tincidunt ut laoreet doloremagna aliquam erat volutpat. Ut wisi enim ad minim veniam,quis nostrud exerci tation ullamcorper suscipit lobortis nislut aliquip ex ea commodo consequat. Duis autem vel eum iriuredolor in hendrerit in vulputate velit esse molestie consequat,vel illum dolore eu feugiat nulla facilisis at vero eros etaccumsan et iusto odio dignissim qui blandit praesent luptatum delenit augue duis dolore te feugait nulla facilisi.Nam liber tempor cum soluta nobis eleifend option conguenihil imperdiet doming id quod mazim placerat facer possimassum. Typi non habent claritatem insitam; est usus legentisin iis qui facit eorum claritatem. Investigationesemonstraverunt lectores legere me lius quod ii legunt saepius.Claritas est etiam processus dynamicus, qui sequitur mutationemconsuetudium lectorum. Mirum est notare quam littera gothica,quam nunc putamus parum claram, anteposuerit litterarum formashumanitatis per seacula quarta decima et quinta decima. Eodemmodo typi, qui nunc nobis videntur parum clari, fiant sollemnesin futurum.',
    'texto_ab' : 'Camilo Arguello',
    'texto_ab_t' : 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit,sed diam nonummy nibh euismod tincidunt ut laoreet doloremagna aliquam erat volutpat. Ut wisi enim ad minim veniam,quis nostrud exerci tation ullamcorper suscipit lobortis nislut aliquip ex ea commodo consequat. Duis autem vel eum iriuredolor in hendrerit in vulputate velit esse molestie consequat,vel illum dolore eu feugiat nulla facilisis at vero eros etaccumsan et iusto odio dignissim qui blandit praesent luptatum delenit augue duis dolore te feugait nulla facilisi.Nam liber tempor cum soluta nobis eleifend option conguenihil imperdiet doming id quod mazim placerat facer possimassum. Typi non habent claritatem insitam; est usus legentisin iis qui facit eorum claritatem. Investigationesemonstraverunt lectores legere me lius quod ii legunt saepius.Claritas est etiam processus dynamicus, qui sequitur mutationemconsuetudium lectorum. Mirum est notare quam littera gothica,quam nunc putamus parum claram, anteposuerit litterarum formashumanitatis per seacula quarta decima et quinta decima. Eodemmodo typi, qui nunc nobis videntur parum clari, fiant sollemnesin futurum.'
}